### ISSUE TITLE
Installation issues on Linux

### ISSUE THREAD

**Issue by Bala-1998** [Farama-Foundation/MAgent2#17]
TypeError                                 Traceback (most recent call last)
[/tmp/ipykernel_30974/3606283676.py](https://file+.vscode-resource.vscode-cdn.net/tmp/ipykernel_30974/3606283676.py) in 
----> 1 from magent2.environments import battle_v4, adversarial_pursuit_v4, tiger_deer_v4
      2 import sys, os
      3 from pettingzoo.utils import random_demo
      4 import pygame
      5 import torch

[~/miniconda3/envs/ai_env/lib/python3.7/site-packages/magent2/__init__.py](https://file+.vscode-resource.vscode-cdn.net/home/bala/The-Learning-Shoal/src/tests/~/miniconda3/envs/ai_env/lib/python3.7/site-packages/magent2/__init__.py) in 
----> 1 from magent2 import gridworld, utility
      2 from magent2.render import Renderer
      3 
      4 # some alias
      5 GridWorld = gridworld.GridWorld

[~/miniconda3/envs/ai_env/lib/python3.7/site-packages/magent2/gridworld.py](https://file+.vscode-resource.vscode-cdn.net/home/bala/The-Learning-Shoal/src/tests/~/miniconda3/envs/ai_env/lib/python3.7/site-packages/magent2/gridworld.py) in 
    119 
    120 
--> 121 class Config:
    122     """Configuration class for a Gridworld game."""
    123 

[~/miniconda3/envs/ai_env/lib/python3.7/site-packages/magent2/gridworld.py](https://file+.vscode-resource.vscode-cdn.net/home/bala/The-Learning-Shoal/src/tests/~/miniconda3/envs/ai_env/lib/python3.7/site-packages/magent2/gridworld.py) in Config()
    191         receiver: list[AgentSymbol],
...
--> 193         terminal: bool = False,
    194     ):
    195         """Add a reward rule.

TypeError: 'type' object is not subscriptable

**Comment by Bala-1998** [comment]
Can you please tell me the issue with the type error?

**Comment by jkterry1** [comment]
Hey @Bala-1998 ! I'm just now looking into all the issues with this repo, apologies for the delayed reply. This issue doesn't have enough information for us to be able to reproduce your error and it's been over a year so I'm going to close this issue, but please let me know if you have any additional questions.
