### ISSUE TITLE
Is there any pre-trained model or scripted AI?

### ISSUE THREAD

**Issue by giangbang** [Farama-Foundation/MAgent2#29]
Hello!

I'm currently interested in cooperative MARL with a large number of agents and I think that MAgent2 is an amazing platform to prototype new ideas. Unfortunately, it seems that MAgent only supports competitive scenarios. Do you have any pre-trained model or scripted AI in specific environments such as battle or Combined arms? I want to use them as fixed opponents to bypass the need for self-playing. 

Thank you!

**Comment by jkterry1** [comment]
Hey there- unfortunately, there currently isn't a pre trained script for this available with this repo.
