### ISSUE TITLE
How to know if an agent is in another's attack range?

### ISSUE THREAD

**Issue by ElizabethDuo** [Farama-Foundation/MAgent2#5]
Hi there, I would like to know if there is an function to get the bool of if an agent is in another's attack_range, or to get all agents attackable.

If there is not, I know that attack range is set by CircleRange(radius).
Is the radius means  the euclidean distance between two agents?

**Comment by dsctt** [comment]
Hi, there currently is not a function that returns such values. And you are correct about the CircleRange(radius).
